/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgentEscrow {
  export type DealStruct = {
    dealId: BigNumberish;
    buyerAgentId: BigNumberish;
    sellerAgentId: BigNumberish;
    buyerAddress: AddressLike;
    sellerAddress: AddressLike;
    paymentToken: AddressLike;
    amount: BigNumberish;
    serviceDescription: string;
    deliverableHash: string;
    status: BigNumberish;
    createdAt: BigNumberish;
    completedAt: BigNumberish;
    deadline: BigNumberish;
  };

  export type DealStructOutput = [
    dealId: bigint,
    buyerAgentId: bigint,
    sellerAgentId: bigint,
    buyerAddress: string,
    sellerAddress: string,
    paymentToken: string,
    amount: bigint,
    serviceDescription: string,
    deliverableHash: string,
    status: bigint,
    createdAt: bigint,
    completedAt: bigint,
    deadline: bigint
  ] & {
    dealId: bigint;
    buyerAgentId: bigint;
    sellerAgentId: bigint;
    buyerAddress: string;
    sellerAddress: string;
    paymentToken: string;
    amount: bigint;
    serviceDescription: string;
    deliverableHash: string;
    status: bigint;
    createdAt: bigint;
    completedAt: bigint;
    deadline: bigint;
  };

  export type DealStatsStruct = {
    totalDeals: BigNumberish;
    totalVolume: BigNumberish;
    completedDeals: BigNumberish;
    disputedDeals: BigNumberish;
  };

  export type DealStatsStructOutput = [
    totalDeals: bigint,
    totalVolume: bigint,
    completedDeals: bigint,
    disputedDeals: bigint
  ] & {
    totalDeals: bigint;
    totalVolume: bigint;
    completedDeals: bigint;
    disputedDeals: bigint;
  };
}

export interface AgentEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentDeals"
      | "allDealIds"
      | "cancelDeal"
      | "completeDeal"
      | "createDeal"
      | "deals"
      | "disputeDeal"
      | "feeRecipient"
      | "fundDeal"
      | "getAgentDeals"
      | "getDeal"
      | "getRecentDeals"
      | "getStats"
      | "nextDealId"
      | "owner"
      | "platformFeeBps"
      | "renounceOwnership"
      | "resolveDeal"
      | "setFeeRecipient"
      | "setPlatformFee"
      | "startDeal"
      | "stats"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DealCancelled"
      | "DealCompleted"
      | "DealCreated"
      | "DealDisputed"
      | "DealFunded"
      | "DealResolved"
      | "DealStarted"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentDeals",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allDealIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelDeal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeDeal",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createDeal",
    values: [
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      BigNumberish,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "deals", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "disputeDeal",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundDeal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentDeals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecentDeals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextDealId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDeal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startDeal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "agentDeals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allDealIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelDeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeDeal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createDeal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disputeDeal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundDeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentDeals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRecentDeals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextDealId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDeal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startDeal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DealCancelledEvent {
  export type InputTuple = [dealId: BigNumberish];
  export type OutputTuple = [dealId: bigint];
  export interface OutputObject {
    dealId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealCompletedEvent {
  export type InputTuple = [dealId: BigNumberish, deliverableHash: string];
  export type OutputTuple = [dealId: bigint, deliverableHash: string];
  export interface OutputObject {
    dealId: bigint;
    deliverableHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealCreatedEvent {
  export type InputTuple = [
    dealId: BigNumberish,
    buyerAgentId: BigNumberish,
    sellerAgentId: BigNumberish,
    paymentToken: AddressLike,
    amount: BigNumberish,
    serviceDescription: string
  ];
  export type OutputTuple = [
    dealId: bigint,
    buyerAgentId: bigint,
    sellerAgentId: bigint,
    paymentToken: string,
    amount: bigint,
    serviceDescription: string
  ];
  export interface OutputObject {
    dealId: bigint;
    buyerAgentId: bigint;
    sellerAgentId: bigint;
    paymentToken: string;
    amount: bigint;
    serviceDescription: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealDisputedEvent {
  export type InputTuple = [dealId: BigNumberish, reason: string];
  export type OutputTuple = [dealId: bigint, reason: string];
  export interface OutputObject {
    dealId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealFundedEvent {
  export type InputTuple = [dealId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [dealId: bigint, amount: bigint];
  export interface OutputObject {
    dealId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealResolvedEvent {
  export type InputTuple = [
    dealId: BigNumberish,
    buyerRefund: BigNumberish,
    sellerPayment: BigNumberish
  ];
  export type OutputTuple = [
    dealId: bigint,
    buyerRefund: bigint,
    sellerPayment: bigint
  ];
  export interface OutputObject {
    dealId: bigint;
    buyerRefund: bigint;
    sellerPayment: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealStartedEvent {
  export type InputTuple = [dealId: BigNumberish];
  export type OutputTuple = [dealId: bigint];
  export interface OutputObject {
    dealId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): AgentEscrow;
  waitForDeployment(): Promise<this>;

  interface: AgentEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentDeals: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  allDealIds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  cancelDeal: TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;

  completeDeal: TypedContractMethod<
    [dealId: BigNumberish, deliverableHash: string],
    [void],
    "nonpayable"
  >;

  createDeal: TypedContractMethod<
    [
      buyerAgentId: BigNumberish,
      sellerAgentId: BigNumberish,
      sellerAddress: AddressLike,
      paymentToken: AddressLike,
      amount: BigNumberish,
      serviceDescription: string,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  deals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        dealId: bigint;
        buyerAgentId: bigint;
        sellerAgentId: bigint;
        buyerAddress: string;
        sellerAddress: string;
        paymentToken: string;
        amount: bigint;
        serviceDescription: string;
        deliverableHash: string;
        status: bigint;
        createdAt: bigint;
        completedAt: bigint;
        deadline: bigint;
      }
    ],
    "view"
  >;

  disputeDeal: TypedContractMethod<
    [dealId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  fundDeal: TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;

  getAgentDeals: TypedContractMethod<
    [agentId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getDeal: TypedContractMethod<
    [dealId: BigNumberish],
    [AgentEscrow.DealStructOutput],
    "view"
  >;

  getRecentDeals: TypedContractMethod<
    [count: BigNumberish],
    [AgentEscrow.DealStructOutput[]],
    "view"
  >;

  getStats: TypedContractMethod<
    [],
    [AgentEscrow.DealStatsStructOutput],
    "view"
  >;

  nextDealId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveDeal: TypedContractMethod<
    [dealId: BigNumberish, buyerRefundPct: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFeeRecipient: TypedContractMethod<
    [newRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  startDeal: TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;

  stats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalDeals: bigint;
        totalVolume: bigint;
        completedDeals: bigint;
        disputedDeals: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentDeals"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "allDealIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelDeal"
  ): TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeDeal"
  ): TypedContractMethod<
    [dealId: BigNumberish, deliverableHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createDeal"
  ): TypedContractMethod<
    [
      buyerAgentId: BigNumberish,
      sellerAgentId: BigNumberish,
      sellerAddress: AddressLike,
      paymentToken: AddressLike,
      amount: BigNumberish,
      serviceDescription: string,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        dealId: bigint;
        buyerAgentId: bigint;
        sellerAgentId: bigint;
        buyerAddress: string;
        sellerAddress: string;
        paymentToken: string;
        amount: bigint;
        serviceDescription: string;
        deliverableHash: string;
        status: bigint;
        createdAt: bigint;
        completedAt: bigint;
        deadline: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "disputeDeal"
  ): TypedContractMethod<
    [dealId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundDeal"
  ): TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgentDeals"
  ): TypedContractMethod<[agentId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getDeal"
  ): TypedContractMethod<
    [dealId: BigNumberish],
    [AgentEscrow.DealStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecentDeals"
  ): TypedContractMethod<
    [count: BigNumberish],
    [AgentEscrow.DealStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<[], [AgentEscrow.DealStatsStructOutput], "view">;
  getFunction(
    nameOrSignature: "nextDealId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDeal"
  ): TypedContractMethod<
    [dealId: BigNumberish, buyerRefundPct: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[newRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[newFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startDeal"
  ): TypedContractMethod<[dealId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalDeals: bigint;
        totalVolume: bigint;
        completedDeals: bigint;
        disputedDeals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DealCancelled"
  ): TypedContractEvent<
    DealCancelledEvent.InputTuple,
    DealCancelledEvent.OutputTuple,
    DealCancelledEvent.OutputObject
  >;
  getEvent(
    key: "DealCompleted"
  ): TypedContractEvent<
    DealCompletedEvent.InputTuple,
    DealCompletedEvent.OutputTuple,
    DealCompletedEvent.OutputObject
  >;
  getEvent(
    key: "DealCreated"
  ): TypedContractEvent<
    DealCreatedEvent.InputTuple,
    DealCreatedEvent.OutputTuple,
    DealCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DealDisputed"
  ): TypedContractEvent<
    DealDisputedEvent.InputTuple,
    DealDisputedEvent.OutputTuple,
    DealDisputedEvent.OutputObject
  >;
  getEvent(
    key: "DealFunded"
  ): TypedContractEvent<
    DealFundedEvent.InputTuple,
    DealFundedEvent.OutputTuple,
    DealFundedEvent.OutputObject
  >;
  getEvent(
    key: "DealResolved"
  ): TypedContractEvent<
    DealResolvedEvent.InputTuple,
    DealResolvedEvent.OutputTuple,
    DealResolvedEvent.OutputObject
  >;
  getEvent(
    key: "DealStarted"
  ): TypedContractEvent<
    DealStartedEvent.InputTuple,
    DealStartedEvent.OutputTuple,
    DealStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DealCancelled(uint256)": TypedContractEvent<
      DealCancelledEvent.InputTuple,
      DealCancelledEvent.OutputTuple,
      DealCancelledEvent.OutputObject
    >;
    DealCancelled: TypedContractEvent<
      DealCancelledEvent.InputTuple,
      DealCancelledEvent.OutputTuple,
      DealCancelledEvent.OutputObject
    >;

    "DealCompleted(uint256,string)": TypedContractEvent<
      DealCompletedEvent.InputTuple,
      DealCompletedEvent.OutputTuple,
      DealCompletedEvent.OutputObject
    >;
    DealCompleted: TypedContractEvent<
      DealCompletedEvent.InputTuple,
      DealCompletedEvent.OutputTuple,
      DealCompletedEvent.OutputObject
    >;

    "DealCreated(uint256,uint256,uint256,address,uint256,string)": TypedContractEvent<
      DealCreatedEvent.InputTuple,
      DealCreatedEvent.OutputTuple,
      DealCreatedEvent.OutputObject
    >;
    DealCreated: TypedContractEvent<
      DealCreatedEvent.InputTuple,
      DealCreatedEvent.OutputTuple,
      DealCreatedEvent.OutputObject
    >;

    "DealDisputed(uint256,string)": TypedContractEvent<
      DealDisputedEvent.InputTuple,
      DealDisputedEvent.OutputTuple,
      DealDisputedEvent.OutputObject
    >;
    DealDisputed: TypedContractEvent<
      DealDisputedEvent.InputTuple,
      DealDisputedEvent.OutputTuple,
      DealDisputedEvent.OutputObject
    >;

    "DealFunded(uint256,uint256)": TypedContractEvent<
      DealFundedEvent.InputTuple,
      DealFundedEvent.OutputTuple,
      DealFundedEvent.OutputObject
    >;
    DealFunded: TypedContractEvent<
      DealFundedEvent.InputTuple,
      DealFundedEvent.OutputTuple,
      DealFundedEvent.OutputObject
    >;

    "DealResolved(uint256,uint256,uint256)": TypedContractEvent<
      DealResolvedEvent.InputTuple,
      DealResolvedEvent.OutputTuple,
      DealResolvedEvent.OutputObject
    >;
    DealResolved: TypedContractEvent<
      DealResolvedEvent.InputTuple,
      DealResolvedEvent.OutputTuple,
      DealResolvedEvent.OutputObject
    >;

    "DealStarted(uint256)": TypedContractEvent<
      DealStartedEvent.InputTuple,
      DealStartedEvent.OutputTuple,
      DealStartedEvent.OutputObject
    >;
    DealStarted: TypedContractEvent<
      DealStartedEvent.InputTuple,
      DealStartedEvent.OutputTuple,
      DealStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
