/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ReputationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentClients"
      | "appendResponse"
      | "cumulativeScore"
      | "feedbacks"
      | "getClients"
      | "getIdentityRegistry"
      | "getLastIndex"
      | "getSummary"
      | "giveFeedback"
      | "identityRegistry"
      | "lastIndex"
      | "owner"
      | "quickFeedback"
      | "readFeedback"
      | "renounceOwnership"
      | "revokeFeedback"
      | "totalFeedbackCount"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeedbackRevoked"
      | "NewFeedback"
      | "OwnershipTransferred"
      | "ResponseAppended"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentClients",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "appendResponse",
    values: [BigNumberish, AddressLike, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cumulativeScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feedbacks",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClients",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getIdentityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLastIndex",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSummary",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "giveFeedback",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      string,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastIndex",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quickFeedback",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "readFeedback",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeFeedback",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeedbackCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentClients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "appendResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cumulativeScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feedbacks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getClients", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getIdentityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSummary", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "giveFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastIndex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quickFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeedbackCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace FeedbackRevokedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    clientAddress: AddressLike,
    feedbackIndex: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    clientAddress: string,
    feedbackIndex: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    clientAddress: string;
    feedbackIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewFeedbackEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    clientAddress: AddressLike,
    feedbackIndex: BigNumberish,
    value: BigNumberish,
    valueDecimals: BigNumberish,
    indexedTag1: string,
    tag1: string,
    tag2: string,
    endpoint: string,
    feedbackURI: string,
    feedbackHash: BytesLike
  ];
  export type OutputTuple = [
    agentId: bigint,
    clientAddress: string,
    feedbackIndex: bigint,
    value: bigint,
    valueDecimals: bigint,
    indexedTag1: string,
    tag1: string,
    tag2: string,
    endpoint: string,
    feedbackURI: string,
    feedbackHash: string
  ];
  export interface OutputObject {
    agentId: bigint;
    clientAddress: string;
    feedbackIndex: bigint;
    value: bigint;
    valueDecimals: bigint;
    indexedTag1: string;
    tag1: string;
    tag2: string;
    endpoint: string;
    feedbackURI: string;
    feedbackHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResponseAppendedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    clientAddress: AddressLike,
    feedbackIndex: BigNumberish,
    responder: AddressLike,
    responseURI: string,
    responseHash: BytesLike
  ];
  export type OutputTuple = [
    agentId: bigint,
    clientAddress: string,
    feedbackIndex: bigint,
    responder: string,
    responseURI: string,
    responseHash: string
  ];
  export interface OutputObject {
    agentId: bigint;
    clientAddress: string;
    feedbackIndex: bigint;
    responder: string;
    responseURI: string;
    responseHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationRegistry;
  waitForDeployment(): Promise<this>;

  interface: ReputationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentClients: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  appendResponse: TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      feedbackIndex: BigNumberish,
      responseURI: string,
      responseHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  cumulativeScore: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  feedbacks: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: BigNumberish],
    [
      [bigint, bigint, string, string, boolean, bigint] & {
        value: bigint;
        valueDecimals: bigint;
        tag1: string;
        tag2: string;
        isRevoked: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getClients: TypedContractMethod<[agentId: BigNumberish], [string[]], "view">;

  getIdentityRegistry: TypedContractMethod<[], [string], "view">;

  getLastIndex: TypedContractMethod<
    [agentId: BigNumberish, clientAddress: AddressLike],
    [bigint],
    "view"
  >;

  getSummary: TypedContractMethod<
    [agentId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        count: bigint;
        totalScore: bigint;
        averageScore: bigint;
      }
    ],
    "view"
  >;

  giveFeedback: TypedContractMethod<
    [
      agentId: BigNumberish,
      value: BigNumberish,
      valueDecimals: BigNumberish,
      tag1: string,
      tag2: string,
      endpoint: string,
      feedbackURI: string,
      feedbackHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  lastIndex: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  quickFeedback: TypedContractMethod<
    [agentId: BigNumberish, value: BigNumberish],
    [void],
    "nonpayable"
  >;

  readFeedback: TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      feedbackIndex: BigNumberish
    ],
    [
      [bigint, bigint, string, string, boolean] & {
        value: bigint;
        valueDecimals: bigint;
        tag1: string;
        tag2: string;
        isRevoked: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeFeedback: TypedContractMethod<
    [agentId: BigNumberish, feedbackIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalFeedbackCount: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentClients"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "appendResponse"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      feedbackIndex: BigNumberish,
      responseURI: string,
      responseHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cumulativeScore"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "feedbacks"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: BigNumberish],
    [
      [bigint, bigint, string, string, boolean, bigint] & {
        value: bigint;
        valueDecimals: bigint;
        tag1: string;
        tag2: string;
        isRevoked: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClients"
  ): TypedContractMethod<[agentId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getIdentityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLastIndex"
  ): TypedContractMethod<
    [agentId: BigNumberish, clientAddress: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSummary"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        count: bigint;
        totalScore: bigint;
        averageScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "giveFeedback"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      value: BigNumberish,
      valueDecimals: BigNumberish,
      tag1: string,
      tag2: string,
      endpoint: string,
      feedbackURI: string,
      feedbackHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastIndex"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quickFeedback"
  ): TypedContractMethod<
    [agentId: BigNumberish, value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "readFeedback"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      clientAddress: AddressLike,
      feedbackIndex: BigNumberish
    ],
    [
      [bigint, bigint, string, string, boolean] & {
        value: bigint;
        valueDecimals: bigint;
        tag1: string;
        tag2: string;
        isRevoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeFeedback"
  ): TypedContractMethod<
    [agentId: BigNumberish, feedbackIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalFeedbackCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FeedbackRevoked"
  ): TypedContractEvent<
    FeedbackRevokedEvent.InputTuple,
    FeedbackRevokedEvent.OutputTuple,
    FeedbackRevokedEvent.OutputObject
  >;
  getEvent(
    key: "NewFeedback"
  ): TypedContractEvent<
    NewFeedbackEvent.InputTuple,
    NewFeedbackEvent.OutputTuple,
    NewFeedbackEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ResponseAppended"
  ): TypedContractEvent<
    ResponseAppendedEvent.InputTuple,
    ResponseAppendedEvent.OutputTuple,
    ResponseAppendedEvent.OutputObject
  >;

  filters: {
    "FeedbackRevoked(uint256,address,uint64)": TypedContractEvent<
      FeedbackRevokedEvent.InputTuple,
      FeedbackRevokedEvent.OutputTuple,
      FeedbackRevokedEvent.OutputObject
    >;
    FeedbackRevoked: TypedContractEvent<
      FeedbackRevokedEvent.InputTuple,
      FeedbackRevokedEvent.OutputTuple,
      FeedbackRevokedEvent.OutputObject
    >;

    "NewFeedback(uint256,address,uint64,int128,uint8,string,string,string,string,string,bytes32)": TypedContractEvent<
      NewFeedbackEvent.InputTuple,
      NewFeedbackEvent.OutputTuple,
      NewFeedbackEvent.OutputObject
    >;
    NewFeedback: TypedContractEvent<
      NewFeedbackEvent.InputTuple,
      NewFeedbackEvent.OutputTuple,
      NewFeedbackEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ResponseAppended(uint256,address,uint64,address,string,bytes32)": TypedContractEvent<
      ResponseAppendedEvent.InputTuple,
      ResponseAppendedEvent.OutputTuple,
      ResponseAppendedEvent.OutputObject
    >;
    ResponseAppended: TypedContractEvent<
      ResponseAppendedEvent.InputTuple,
      ResponseAppendedEvent.OutputTuple,
      ResponseAppendedEvent.OutputObject
    >;
  };
}
